

-- USADO PARA ACTUALIZAR NOMBRE DE UN SECTOR
	CREATE OR ALTER PROCEDURE HL.sp_actualizarSector
		@ID_SECTOR NUMERIC(18, 0),
		@NOMBRE_SECTOR NVARCHAR(255)
	AS BEGIN
		UPDATE HL.sectores
			SET nombreSectorUSUARIO = @NOMBRE_SECTOR
			WHERE idSector = @ID_SECTOR
	END


-- USADO PARA ACTUALIZAR NÚMERO-NOMBRE-DESCRIPCIÓN DE UNA MÁQUINA
	CREATE OR ALTER PROCEDURE HL.sp_actualizarMaquina
		@ID_MAQUINA NUMERIC(18, 0),
		@NUMERO_MAQUINA SMALLINT,
		@NOMBRE_MAQUINA NVARCHAR(255),
		@DESCRIPCION_MAQUINA NVARCHAR(255)
	AS BEGIN
		UPDATE HL.maquinas
			SET numeroMaquinaUSUARIO = @NUMERO_MAQUINA,
				nombreMaquinaUSUARIO = @NOMBRE_MAQUINA,
				descripcionMaquinaUSUARIO = @DESCRIPCION_MAQUINA
			WHERE idMaquina = @ID_MAQUINA
	END


	